config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  get 'portfolio/:id/delete', to: 'portfolios#delete', as: 'portfolio_delete'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  # mount ActionCable.server => '/cable'
  
  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="text-muted mastfoot">
<div class="inner">
  <div class="container">
     <p class="app-footer"><%= @copyright %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<div class="navbar-style collapse" id="navbarHeader">
  <div class="container nav-list">
    <div class="row">
      <div class="col-md-8 py-4">
        <%= nav_helper 'navitem-space nav-left', 'span' %>
        <%= login_helper %>
      </div>
      <div class="nav-right col-md-4 py-4">
           <h3>iOS + Rails Developer</h3>
        </div>
    </div>
  </div>
</div>

<div class="navbar-style navbar navbar-inverse ">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Max Asher Nelson</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
          <div class="mastfoot">
            <div class="inner">
              <p class="app-footer"><%= @copyright %></p>
            </div>
          </div>

app/views/shared/_blog_masthead.html.erb
    <div class="blog-header">
      <div class="container">
        <h1 class="blog-title">Max's Blog</h1>
        <p class="lead blog-description">Infos</p>

        <span>
          <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
        </span>
        -
        <span>
          <%= link_to 'Topics', topics_path %>
        </span>

      </div>
    </div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container">
    <%= link_to "Max Nelson", root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper 'nav-link', 'li' %>  
        <%= login_helper 'nav-link' %>  
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>I attend Utah Valley University studying Computer Science. I work at Gadzoom.net as an iOS Developer</p>
  </div>

  <%= source_helper("alert alert-info blog-sidebar-source") %>

  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

  <div class="sidebar-module">
    <h4>Im All Over The World Wide Web!</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://www.linkedin.com/in/maxwellnelson/"><%= fa_icon "linkedin" %></a></li>
      <li><a href="https://github.com/Maxnelson997"><%= fa_icon "github" %></a></li>
      <li><a href="https://stackoverflow.com/users/3778273/max-nelson"><%= fa_icon "stack-overflow" %></a></li>
      <li><a href="https://www.instagram.com/superdupermaxwellsue/"><%= fa_icon "instagram" %></a></li>
      <li><a href="https://www.youtube.com/MAXNELSON"><%= fa_icon "youtube" %></a></li>
      <li><a href="https://twitter.com/MaximusAsher"><%= fa_icon "twitter" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %> navlinks">
	<div class="container">
		<div class="row">
			<div class="col-md-7">
			  <div><%= link_to "Home", root_path %></div>
			  <div><%= link_to "About Ur Boi Max", about_me_path %></div>
			  <div><%= link_to "Contact", contact_path %></div>
			</div>
			<div class="col-md-5">
			  <div><%= link_to "Blog", blogs_path %></div>
			  <div><%= link_to "Portfolio", portfolios_path %></div>
			</div>
		</div>
	</div>
</div>

app/views/shared/_porfolio_masthead.html.erb
<section class="jumbotron text-center">

  <div class="container">

    <h1 class="jumbotron-heading">iOS Projects</h1>
    <p class="lead text-muted">Work I have done for clients</p>
    <p>
      <%= link_to 'Find out more about me', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blogs', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View All Portfolio Items", portfolios_path %> /
      <a href="#">Back to top</a>
    </p>

    <p>
      <%= @copyright %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">Check this junk out</h4>
        <p class="text-muted">I am an iOS Developer, Clearly.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Contact</h4>
        <ul class="list-unstyled">
            <%= nav_helper 'text-white', 'li' %>
            <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Max Asher Nelson</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>